import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Burnout Buster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h5>HIYA!</h5>
        <h2>Welcome to</h2>
        <h2 className={inter.className}>
          Burnout Buster
        </h2>
        <p>We know that dealing with burnout can be a difficult and stressful experience, and finding the right resources can be overwhelming. Our goal is to make it easier for you to find the help you need by offering a personalized search experience that will connect you with the resources and support you need to recover and thrive.</p>
        <button>Begin Quiz</button>
      </main>
    </>
  )
}
